interface User {
    id?: string;
    first_name?: string;
    last_name?: string;
    username?: string;
    display_name?: string;
    bio?: string;
    avatar?: string;
    banner_image?: string;
    twitter_page?: string;
    facebook_page?: string;
    instagram_page?: string;
    snapchat_page?: string;
    tiktok_page?: string;
    twitch_page?: string;
    youtube_page?: string;
    paetron_page?: string;
    twitter_handle?: string;
    facebook_handle?: string;
    instagram_handle?: string;
    snapchat_handle?: string;
    tiktok_handle?: string;
    twitch_handle?: string;
    youtube_handle?: string;
    paetron_handle?: string;
    gmail_oauth_token?: string;
    gmail_refresh_token?: string;
    gmail_token_expiration?: number;
    gmail_token_expires_at?: string;
    gmail_id?: string;
    gmail_name?: string;
    gmail_email?: string;
    gmail_avatar?: string;
    gmail_scopes?: string[];
    gmail_connected_at?: string;
    created_at?: string;
    updated_at?: string;
  }

  export default User;
